---
title: "Updates and In-Class Assignments"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: journal
---

-----

# In-class Exercise: 09-28

## Deciphering a Program

Below you'll find a snippet of some code that we work with in my [Technologies of Text](http://s17tot.ryancordell.org/) class. Today I just want to look at the code together and work to decipher it. You'll be in groups and I want you to try and answer, to the best of your ability:

1. From what point does the code begin? In other words, what's its source data?
2. What does this code *do*? When it's run, what is the final product?
3. How does the code get from its source data to that final product? Which of the intervening steps can you separate out and understand?
4. This last step is more abstract, but how are the operations of this code *similar* to writing, and how are they *distinct*?

# Mystery Code

```{r, eval = FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=50)}
my_wordnik_key <- "YOUR_API_KEY_GOES_HERE"

#the line below will set the "default" part of speech for your calls to Wordnik, but you will be able to override this setting in later code.
wordnik_pos = "adjective"

#
random_word <- function(key=my_wordnik_key,
                        pos=wordnik_pos, min_count=100, n=1,
                        min_length = 5, max_length = 10){
  
  param <- paste0("words.json/randomWords?hasDictionaryDef=true",
                  "&minCorpusCount=",min_count,
                  "&minLength=",min_length,
                  "&maxLength=",max_length,
                  "&limit=",n,
                  "&includePartOfSpeech=",pos)

  raw = birdnik:::query(key = key,params = param)
  do.call(rbind,lapply(raw,as.data.frame))
  
}

random_word(pos="verb",n=5, min_count=1000)
random_word(pos="interjection",n=10, min_count=100)

poem_word <- function(x) {
  random_word(pos=x,n=1,min_count=1000)[,2] %>%
    as.character()
}

poem_word("interjection")

poem <- paste(c(poem_word("verb"), " thy ", poem_word("noun"), " from ", poem_word("preposition")," my ", poem_word("noun"), ", and ", poem_word("verb"), " thy ", poem_word("noun"), " from ", poem_word("preposition"), " my ", poem_word("noun"), "! \nQuoth the Ravbot, '", poem_word("interjection"), "!'"), collapse = "")

cat(poem)

setup_twitter_oauth("YOUR_CONSUMER_KEY_GOES_HERE", 
                    "YOUR_CONSUMER_SECRET_GOES_HERE", 
                    'YOUR_ACCESS_TOKEN_GOES_HERE', 
                    'YOUR_ACCESS_SECRET_GOES_HERE')

woeid <- "2367105"

trend <- getTrends(woeid)[,1] %>%
  as_data_frame() %>%
  rename(trend = value) %>%
  filter(grepl("^#", trend))

poem <- paste(c(poem_word("verb"), " thy ", poem_word("noun"), " from ", poem_word("preposition")," my ", poem_word("noun"), ", and ", poem_word("verb"), " thy ", poem_word("noun"), " from ", poem_word("preposition"), " my ", poem_word("noun"), '!" \nQuoth the Ravbot, "Never ', trend %>% sample_n(1), "!'"), collapse = "")

cat(poem)

if(nchar(poem) < 140) {
  tweet(poem)
  } else {
    print("The poem is too long. Please rerun the generator and try again!")
  }
```

-----

# In-class Writing Prompt: 09-27
## ["The Truth of Fact, the Truth of Feeling"](https://subterraneanpress.com/magazine/fall_2013/the_truth_of_fact_the_truth_of_feeling_by_ted_chiang) by Ted Chiang

What is a memory? Increasingly, scientists are learning that memories are physically encoded in the brain. Scientists have even found ways to [suppress the formation of memories or selectively erase them](http://www.radiolab.org/story/91570-eternal-sunshine-of-the-spotless-rat/). Some of the best evidence, in fact, suggests that memories are reformed in the brain each time they are recalled, and that in fact the more often we recall something, [the less accurate that memory becomes](https://news.northwestern.edu/stories/2012/09/your-memory-is-like-the-telephone-game). Each time we remember something, we remember not the original event but instead our previous recollection of it, including all of the new ideas, connections, emotions, and other new contexts we've since associated with that memory. If you recall a moment with a dear childhood friend with whom you've since had a falling out, that memory will be tinged with anger, or sadness, or regret, and that tinge will echo through all future recollections of that moment, subtly reshaping it over time. 

Given all that, would you sign up for Remem if it were available? Why or why not?

-----

# In-class Writing Prompt: 09-18

Choose one of the following quotes about *17776*, one more about the form of the story and the other is more about its content. Either way, use your chosen quote to reflect on the story. You can take any path you'd like, but use specific examples if at all possible. 

1. The first comes from [an online Q&A with the author of *17776*, SBNation (Sports Blog Nation) creative director Jon Bois](https://www.sbnation.com/2017/7/24/16003968/17776-questions-and-answers). When "@Crazyeyesdave" asked, "Do you think weird experimental stories like this have a future in sports writing or was this a singular event?" Bois responded:
    
    > I hope so. Maybe not distant-future sports sci-fi, but that’s only one of a thousand lanes. I could go really, really long on this answer. I’ll keep it short: There are countless different ways to write, and things and ideas to write about. And the Internet offers a kaleidoscope of different formats, media, tools, sights, and sounds to tell your stories. And most of us are not even trying to scrape the surface of any of it. We’ve got to start thinking of the Internet as something more than a glow-in-the-dark newspaper.

2. In a post about *17776* at the A.V. club, [William Hughes takes a more philosophical bent](https://news.avclub.com/the-future-of-football-is-post-human-despair-and-fasci-1798263717), arguing that: 
    
    > "Bois’ serial story...seems largely concerned with the “why” of sports. That is, given the massive resources, time, and information at our disposal (not to mention those available to our descendants), why does communal game-playing still hold such an important place in society?"